"""Comprehensive material properties database"""

MATERIAL_DATABASE = {
    # 3D Printing Materials
    "PLA": {
        "category": "thermoplastic",
        "density_g_cm3": 1.25,
        "tensile_strength_mpa": 50,
        "yield_strength_mpa": 40,
        "elastic_modulus_mpa": 3500,
        "poisson_ratio": 0.36,
        "thermal_expansion_ppm_c": 68,
        "max_temp_c": 60,
        "glass_transition_c": 60,
        "melting_point_c": 160,
        "cost_per_kg_usd": 20,
        "printability": "excellent",
        "post_processing": ["sanding", "painting", "acetone_smoothing"],
        "applications": ["prototypes", "non-functional", "indoor"],
        "food_safe": True
    },
    "ABS": {
        "category": "thermoplastic",
        "density_g_cm3": 1.05,
        "tensile_strength_mpa": 40,
        "yield_strength_mpa": 35,
        "elastic_modulus_mpa": 2300,
        "poisson_ratio": 0.35,
        "thermal_expansion_ppm_c": 90,
        "max_temp_c": 98,
        "glass_transition_c": 105,
        "melting_point_c": 200,
        "cost_per_kg_usd": 25,
        "printability": "good",
        "post_processing": ["sanding", "painting", "acetone_smoothing"],
        "applications": ["functional", "enclosures", "automotive"],
        "food_safe": False
    },
    "PETG": {
        "category": "thermoplastic",
        "density_g_cm3": 1.27,
        "tensile_strength_mpa": 53,
        "yield_strength_mpa": 45,
        "elastic_modulus_mpa": 2070,
        "poisson_ratio": 0.38,
        "thermal_expansion_ppm_c": 60,
        "max_temp_c": 73,
        "glass_transition_c": 80,
        "melting_point_c": 230,
        "cost_per_kg_usd": 30,
        "printability": "good",
        "post_processing": ["sanding", "painting"],
        "applications": ["functional", "outdoor", "containers"],
        "food_safe": True,
        "chemical_resistant": True
    },
    "Nylon": {
        "category": "thermoplastic",
        "density_g_cm3": 1.14,
        "tensile_strength_mpa": 75,
        "yield_strength_mpa": 45,
        "elastic_modulus_mpa": 1600,
        "poisson_ratio": 0.39,
        "thermal_expansion_ppm_c": 80,
        "max_temp_c": 178,
        "glass_transition_c": 47,
        "melting_point_c": 220,
        "cost_per_kg_usd": 80,
        "printability": "moderate",
        "post_processing": ["dyeing", "painting"],
        "applications": ["gears", "bearings", "living_hinges", "functional"],
        "moisture_absorption": True,
        "flexible": True
    },
    "TPU": {
        "category": "thermoplastic_elastomer",
        "density_g_cm3": 1.21,
        "tensile_strength_mpa": 35,
        "yield_strength_mpa": 25,
        "elastic_modulus_mpa": 26,
        "shore_hardness": "95A",
        "elongation_percent": 450,
        "thermal_expansion_ppm_c": 120,
        "max_temp_c": 80,
        "cost_per_kg_usd": 60,
        "printability": "moderate",
        "applications": ["flexible_parts", "gaskets", "grips"],
        "flexible": True
    },
    "Carbon_Fiber_PLA": {
        "category": "composite",
        "density_g_cm3": 1.30,
        "tensile_strength_mpa": 70,
        "yield_strength_mpa": 60,
        "elastic_modulus_mpa": 5500,
        "poisson_ratio": 0.35,
        "thermal_expansion_ppm_c": 50,
        "max_temp_c": 60,
        "cost_per_kg_usd": 120,
        "printability": "moderate",
        "applications": ["structural", "high_stiffness", "lightweight"],
        "abrasive": True,
        "requires_hardened_nozzle": True
    },
    
    # Metals
    "Aluminum_6061": {
        "category": "metal",
        "density_g_cm3": 2.70,
        "tensile_strength_mpa": 310,
        "yield_strength_mpa": 276,
        "elastic_modulus_mpa": 68900,
        "poisson_ratio": 0.33,
        "thermal_expansion_ppm_c": 23.6,
        "thermal_conductivity_w_mk": 167,
        "max_temp_c": 582,
        "melting_point_c": 582,
        "cost_per_kg_usd": 15,
        "machinability": "excellent",
        "weldability": "good",
        "corrosion_resistance": "excellent",
        "applications": ["structural", "aerospace", "frames", "enclosures"],
        "anodizable": True
    },
    "Steel_1045": {
        "category": "metal",
        "density_g_cm3": 7.85,
        "tensile_strength_mpa": 620,
        "yield_strength_mpa": 450,
        "elastic_modulus_mpa": 205000,
        "poisson_ratio": 0.29,
        "thermal_expansion_ppm_c": 11.5,
        "thermal_conductivity_w_mk": 49.8,
        "max_temp_c": 1500,
        "melting_point_c": 1500,
        "cost_per_kg_usd": 5,
        "machinability": "good",
        "weldability": "excellent",
        "applications": ["shafts", "gears", "structural", "high_load"],
        "heat_treatable": True
    },
    "Stainless_316": {
        "category": "metal",
        "density_g_cm3": 8.00,
        "tensile_strength_mpa": 515,
        "yield_strength_mpa": 205,
        "elastic_modulus_mpa": 193000,
        "poisson_ratio": 0.30,
        "thermal_expansion_ppm_c": 15.9,
        "thermal_conductivity_w_mk": 16.3,
        "max_temp_c": 1400,
        "melting_point_c": 1400,
        "cost_per_kg_usd": 12,
        "machinability": "moderate",
        "weldability": "excellent",
        "corrosion_resistance": "excellent",
        "applications": ["marine", "food_processing", "chemical", "medical"],
        "food_safe": True
    }
}

# Material selection guide
MATERIAL_SELECTION_GUIDE = {
    "high_strength": ["Carbon_Fiber_PLA", "Nylon", "Steel_1045", "Aluminum_6061"],
    "high_temperature": ["Nylon", "Steel_1045", "Stainless_316", "Aluminum_6061"],
    "flexible": ["TPU"],
    "low_cost": ["PLA", "ABS", "Steel_1045"],
    "lightweight": ["PLA", "Carbon_Fiber_PLA", "Aluminum_6061"],
    "outdoor": ["PETG", "ABS", "Aluminum_6061", "Stainless_316"],
    "food_safe": ["PLA", "PETG", "Stainless_316"],
    "chemical_resistant": ["PETG", "Stainless_316"]
}